version: "3.8"
services:
  gofer:
    image: ghcr.io/chronicleprotocol/oracle-suite:dev
    build:
      context: "."
    entrypoint: [ "/usr/local/bin/gofer" ]
    command: [ "agent", "-v", "info" ]
